"""
Phase 7a constants for the FW-UAV6DPose evaluation: model-to-dataset correction, camera, sequence and range settings.

The 3D model (an Unreal Engine OBJ) is in centimetres and its axes differ from the dataset's object frame by a
180 degree rotation about x (verified against the visible-object masks, see phase7a_model_check.py). A model vertex
v_obj in the frame used by the BOP poses (metres) is
    v_obj = MODEL_ROTATION @ (MODEL_UNIT_TO_M * v_file)
and X_camera = R_m2c @ v_obj + t_m2c. The keypoints in KEYPOINTS are in this object frame, in metres.
"""

import numpy as np

MODEL_UNIT_TO_M = 0.01                          # the OBJ is in centimetres
MODEL_ROTATION = np.diag([1.0, -1.0, -1.0])     # 180 degrees about x (file frame -> dataset object frame)

IMAGE_W, IMAGE_H = 1920, 1080
DT = 0.1                                        # s, assumed (the dataset has no timestamps), as in the simulation
DT_SENSITIVITY = [0.05, 0.2]
NOISES = [0.0, 1.0, 2.0, 5.0]
SEEDS = range(5)
RANGE_BINS_M = [150.0, 250.0, 350.0, 450.0, np.inf]     # evaluation bins (the dataset spans 164-518 m)
CALIB_RANGE_M = (140.0, 540.0)                  # distance range of the synthetic poses used to calibrate R
GLITCH_SPLITS = {"000125": [77]}                # scene -> first frame after the glitch (the jump is between frames 76 and 77)

# ---- keypoints (generated by phase7a_keypoints.py; do not edit by hand) ----
KEYPOINT_NAMES = [
    "nose",
    "tail",
    "fin_top",
    "stabiliser_tip_left",
    "stabiliser_tip_right",
    "wingtip_left_leading",
    "wingtip_left_trailing",
    "wing_root_left_leading",
    "wing_root_left_trailing",
    "wingtip_right_leading",
    "wingtip_right_trailing",
    "wing_root_right_leading",
    "wing_root_right_trailing",
]
KEYPOINTS = np.array([
    [0.115, -0.268, 0.134],
    [-18.358, -0.268, -3.425],
    [-17.156, -0.260, -3.526],
    [-18.033, -4.318, -3.425],
    [-18.033, 3.782, -3.425],
    [-5.871, -16.262, -1.128],
    [-8.444, -16.007, -1.006],
    [0.544, -4.022, -1.091],
    [-12.688, -3.922, -1.078],
    [-5.871, 15.738, -1.129],
    [-8.444, 15.483, -1.006],
    [0.546, 3.917, -1.089],
    [-12.303, 3.957, -1.114],
])
